### ISSUE TITLE
Prices Not Updating

### ISSUE THREAD

**Issue by rdc000** [0xz00n/EDPriceCheckBot#4]
Looks like the linked bot has lost its EDDN connection. 

Prices have been unchanged (and wrong) for a few days now.

I added it to a fresh test server and am getting the same wrong values as a public server I am on.

**Comment by 0xz00n** [comment]
Thanks for letting me know!  I've kicked the bot and it should be responding again.  Your guess was spot on.  It hit a weird condition and stopped updating.  I'll have to look into what's causing it when I've got a moment.
